sb/SmallBasicWebsite

angular.json
Reverts Caseysch/SmallBasicWebsite#2
=> Revert "Update deployUrl"

src/app/home/home.component.html
=> Updating starting coding link.

src/app/app-routing.module.ts, src/app/tutorial/tutorial.component.css, src/app/tutorial/tutorial.component.html, src/app/tutorial/tutorial.component.ts
Automatically navigate to chapter 1, make the tutorial navigation prettier, add sample anchor links.
Issue: #18
=> Update tutorial navigation

package-lock.json, src/app/contact/contact.component.html
=> Add Contact Information to Contact Page (#15)

src/app/tutorial/tutorial.component.css
=> Make the tutorials menu pass Keros checks

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/page-not-found/page-not-found.component.css, src/app/page-not-found/page-not-found.component.html, src/app/page-not-found/page-not-found.component.spec.ts, src/app/page-not-found/page-not-found.component.ts
=> Add 404 Page

src/app/app.module.ts, src/app/programs/programs.component.html, src/app/resources/resources.component.css, src/app/resources/resources.component.html, src/app/resources/resources.component.ts
Make resources prettier, remove link to get program featured because it is a lie
=> Restructure resources page

angular.json, src/app/home/home.component.css, src/app/home/home.component.html
I added social media icons and links on the home page: Facebook, Twitter, YouTube, Microsoft forum (Is that last one right?)
I used this library for the icons: https://fontawesome.com/
The icons are just hanging out in a div at the top of the sidebar. There's probably a better place to put them?
=> Added social media buttons to home page

src/app/tutorial/chapters/appendixA/appendixA.component.html, src/app/tutorial/chapters/appendixB/appendixB.component.html, src/app/tutorial/chapters/chapter10/chapter10.component.html, src/app/tutorial/chapters/chapter11/chapter11.component.html, src/app/tutorial/chapters/chapter3/chapter3.component.html, src/app/tutorial/chapters/chapter4/chapter4.component.html, src/app/tutorial/chapters/chapter5/chapter5.component.html, src/app/tutorial/chapters/chapter6/chapter6.component.html, src/app/tutorial/chapters/chapter7/chapter7.component.html, src/app/tutorial/chapters/chapter8/chapter8.component.html, src/app/tutorial/chapters/chapter9/chapter9.component.html, src/app/tutorial/tutorial.component.ts
Removing table of contents from each chapter and adding to left menu
=> removing table of contents from each chapter and adding to left menu

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/resources/resources.component.css, src/app/tutorial/tutorial.component.css, src/app/tutorial/tutorial.component.html, src/app/tutorial/tutorial.component.spec.ts, src/app/tutorial/tutorial.component.ts, src/styles.css
Remove redirect to Chapter 1, detect if on base page or child page, show landing page content if on base page
=> Add a landing page for tutorials so Coding Clubs can add content

src/app/home/home.component.css, src/app/home/home.component.html, src/app/programs/programs.component.css, src/app/programs/programs.component.html, src/app/tutorial/tutorial.component.css
Social media icons cleaned up (app/home). Featured programs mobile ready, padded. Button color matches overall site design. (app/programs)
=> CSS clean up

azure-pipelines.yml, package-lock.json, package.json, src/karma.conf.js
=> Testing test output.

src/app/app.module.ts, src/app/documentation/documentation.component.css, src/app/documentation/documentation.component.html, src/app/documentation/documentation.component.spec.ts, src/app/documentation/documentation.component.ts, src/app/documentation/documentation.service.ts, src/app/sbcode.pipe.spec.ts, src/app/sbcode.pipe.ts, src/app/tutorial/tutorial.component.ts, src/styles.css
Fixes #63
Old on left, new on right
=> Created pipe to mimic colors of SB desktop, made docs page prettier

src/app/app-routing.module.ts, src/app/tutorial/chapters/appendixA/appendixA.component.html, src/app/tutorial/chapters/appendixB/appendixB.component.html, src/app/tutorial/chapters/chapter1/chapter1.component.html, src/app/tutorial/chapters/chapter10/chapter10.component.html, src/app/tutorial/chapters/chapter11/chapter11.component.html, src/app/tutorial/chapters/chapter2/chapter2.component.html, src/app/tutorial/chapters/chapter3/chapter3.component.html, src/app/tutorial/chapters/chapter4/chapter4.component.html, src/app/tutorial/chapters/chapter5/chapter5.component.html, src/app/tutorial/chapters/chapter6/chapter6.component.html, src/app/tutorial/chapters/chapter7/chapter7.component.html, src/app/tutorial/chapters/chapter8/chapter8.component.html, src/app/tutorial/chapters/chapter9/chapter9.component.html
=> Fix Prev/Next Chapter Links to Scroll to Titles

README.md
=> Remove reference to old website url

src/app/resources/resources.component.ts
Can we add the Unique Features page to the SB Introductions card on the upper left? That's an exhaustive deep dive into what makes SB so awesome. Please review this PR.
=> Resources Page - Adding Unique Features

src/app/documentation/documentation.service.ts
I only see these two files in the blob storage account
Fixes #83
=> Label pt-br documentation

src/app/home/home.component.ts
Fixes #113 
Not sure why this started working again but hey
=> Don't redirect mac+safari users anymore

src/app/app.module.ts, src/app/home/home.component.css, src/app/home/home.component.html
=> Add spinner to announcements/forum posts

src/app/app.module.ts, src/app/documentation/documentation.component.css, src/app/documentation/documentation.component.html, src/app/documentation/documentation.component.ts, src/app/documentation/search/search-docs.pipe.ts, src/app/resources/resources.component.ts
And make it a little easier to find, and fix the anchor tags
Fixes #86
=> Add a search for api 
